name: Deploy Application

on:
  workflow_dispatch:
  push:
    branches:
      - jira-sefa-test
      - main
# permissions:
#   contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy application')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Generate Git Tag
        id: generate_tag
        run: |
          set -e
          VERSION_PREFIX="v"
          VERSION_MAJOR_MINOR="2.0"
          VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
          if [ -z "$VERSION_PATCH" ]; then
            VERSION_PATCH=0
          else
            VERSION_PATCH=$((VERSION_PATCH + 1))
          fi
          NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Push Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          set -e
          # git config user.name "chaitanya" # Replace with your name
          # git config user.email "mr.kanneganti6003@gmail.com" # Replace with your email
          git tag $NEW_TAG
          git push origin $NEW_TAG
