name: Deploy Application

on:
  push:
    branches:
      - main
      - jira-sefa-test1
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Select the environment to deploy'
        required: true
        options:
          - main
          - jira-sefa-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'  # Ensure full history for tag creation

      # Generate Git tag if conditions match
      - name: Generate and Push Git Tag
        if: |
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/jira-sefa-test1') &&
          contains(github.event.head_commit.message, 'push_to_master')
        id: generate_tag
        run: |
          set -e
          VERSION_PREFIX="v"
          VERSION_MAJOR_MINOR="2.0"
          VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
          if [ -z "$VERSION_PATCH" ]; then
            VERSION_PATCH=0
          else
            VERSION_PATCH=$((VERSION_PATCH + 1))
          fi
          NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      # Push the generated tag if conditions are met
      - name: Push Git Tag
        if: |
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/jira-sefa-test1') &&
          contains(github.event.head_commit.message, 'push_to_master')
        run: |
          set -e
          git tag $NEW_TAG
          git push origin $NEW_TAG

      # # Optional: Deployment based on the environment choice
      # - name: Deploy to Production
      #   if: ${{ github.event.inputs.choice == 'main' }}
      #   run: |
      #     echo "Deploying to Production..."

      # - name: Deploy to Staging
      #   if: ${{ github.event.inputs.choice == 'jira-sefa-test' }}
      #   run: |
      #     echo "Deploying to Staging..."
